quarkus:
  log:
    level: INFO

    category:
      "io.nop":
        level: ERROR

nop:
  application:
    locale: en

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:test
    username: sa
    password: