nop:
  auth:
    site-map:
      static-config-path: /nop/demo/app.action-auth.xml
      cache-timeout: 1s
      support-debug: true

    #data-auth-config-path: /nop/demo/app.data-auth.xml
    #enable-data-auth: false
    # enable-action-auth: true

    login:
      allow-create-default-user: true # 如果用户表为空，则自动创建缺省账户nop, 密码nop-test
      use-dao-user-context-cache: true

    jwt:
      enc-key: dij3)(4ldt[]erq=2mfKID

  orm:
    init-database-schema: true

  datasource:
    #    driver-class-name: org.h2.Driver
    #    jdbc-url: jdbc:h2:./db/test
    #    username: sa
    #    password:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc-url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    # username: nop
    # password: nop-test
    metrics-enabled: true
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/test
    username: sa
    password:

# 开发模式配置

"%dev":
  nop:
    debug: true
    # log:
    #   level: trace

    auth:
      login:
        allow-create-default-user: true # 如果用户表为空，则自动创建缺省账户nop, 密码nop-test

    datasource:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./db/test
      username: sa
      password:

    orm:
      init-database-schema: true

    # 支持graphql __schema查询，
    graphql:
      schema-introspection:
        enabled: true


# devservices 会启用testcontainers来管理测试数据库
quarkus:
  devservices:
    enabled: false

  datasource:
    devservices:
      enabled: false

  vertx-graphql:
    ui:
      always-include: true


  http:
    host: 0.0.0.0
    cors: true

  log:
    level: info
    min-level: trace

    #    console:
    #      json: true

    category:
      "io.nop":
        level: INFO
      "io.nop.api.core.context":
        level: TRACE
      "io.nop.http.api.server":
        level: TRACE

